/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

/**
 *
 * @author Jaenicx
 */
public class AdminMainForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainForm
     */
    public AdminMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updateLogin = new javax.swing.JButton();
        addStudentLogin = new javax.swing.JButton();
        deleteLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, -1, -1));

        updateLogin.setBackground(new java.awt.Color(51, 51, 255));
        updateLogin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        updateLogin.setForeground(new java.awt.Color(255, 255, 255));
        updateLogin.setText("Update Student");
        updateLogin.setBorder(null);
        updateLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLoginActionPerformed(evt);
            }
        });
        jPanel2.add(updateLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 180, 40));

        addStudentLogin.setBackground(new java.awt.Color(51, 51, 255));
        addStudentLogin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        addStudentLogin.setForeground(new java.awt.Color(255, 255, 255));
        addStudentLogin.setText("Add Student Login");
        addStudentLogin.setBorder(null);
        addStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentLoginActionPerformed(evt);
            }
        });
        jPanel2.add(addStudentLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 40));

        deleteLogin.setBackground(new java.awt.Color(51, 51, 255));
        deleteLogin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        deleteLogin.setForeground(new java.awt.Color(255, 255, 255));
        deleteLogin.setText("Delete Student");
        deleteLogin.setBorder(null);
        deleteLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLoginActionPerformed(evt);
            }
        });
        jPanel2.add(deleteLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 180, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 0, 320, 600));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 560, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLoginActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminUpdateForm update = new AdminUpdateForm();
        update.show();
    }//GEN-LAST:event_updateLoginActionPerformed

    private void addStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentLoginActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminAddLoginForm add = new AdminAddLoginForm();
        add.show();
        
    }//GEN-LAST:event_addStudentLoginActionPerformed

    private void deleteLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLoginActionPerformed
        // TODO add your handling code here:

        this.hide();
        DeleteStudentForm xelete = new DeleteStudentForm();
        xelete.show();
    }//GEN-LAST:event_deleteLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentLogin;
    private javax.swing.JButton deleteLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton updateLogin;
    // End of variables declaration//GEN-END:variables
}
