/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static service.implementation.LibrarySystemImplemenation_JDBC.connString;
import presentation.AdminViewForm;


/**
 *
 * @author Jaenicx
 */
public class AdminAddLoginForm extends javax.swing.JFrame {

    JFrame frame;

    /**
     * Creates new form AdminAddLoginForm
     */
    public AdminAddLoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        usernameBox = new javax.swing.JTextField();
        loginSubmitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        passwordBox = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        idNumberBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 257, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter ID Number:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        usernameBox.setBackground(new java.awt.Color(51, 51, 255));
        usernameBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        usernameBox.setForeground(new java.awt.Color(255, 255, 255));
        usernameBox.setBorder(null);
        usernameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameBoxActionPerformed(evt);
            }
        });
        jPanel2.add(usernameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 30));

        loginSubmitButton.setBackground(new java.awt.Color(51, 51, 255));
        loginSubmitButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        loginSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        loginSubmitButton.setText("Submit");
        loginSubmitButton.setBorder(null);
        loginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 80, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter Password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        passwordBox.setBackground(new java.awt.Color(51, 51, 255));
        passwordBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        passwordBox.setForeground(new java.awt.Color(255, 255, 255));
        passwordBox.setBorder(null);
        passwordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBoxActionPerformed(evt);
            }
        });
        jPanel2.add(passwordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 220, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 257, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Username:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 257, 20));

        idNumberBox.setBackground(new java.awt.Color(51, 51, 255));
        idNumberBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        idNumberBox.setForeground(new java.awt.Color(255, 255, 255));
        idNumberBox.setBorder(null);
        idNumberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNumberBoxActionPerformed(evt);
            }
        });
        jPanel2.add(idNumberBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 0, 310, 600));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 540, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameBoxActionPerformed

    private void loginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitButtonActionPerformed
        // TODO add your handling code here:

        try {
            
            //StudentLogin_Manager stuLogin = new StudentLogin_Manager();
            //stuLogin.studentLogin_Update(Integer.parseInt(idUpdateBox.getText()), usernameUpdateBox.getText(), passwordUpdateBox.getName());
            // LibrarySystemImplemenation_JDBC lib = new LibrarySystemImplemenation_JDBC();
            // lib.student_Insert(Integer.parseInt(studentIDBox.getText()), fnameBox.getText(), lnameBox.getText(), mailBox.getText());
            try {

                domain.StudentLogin login = new domain.StudentLogin();
                login.setUsername(usernameBox.getText());
                login.setPassword(passwordBox.getText());
                login.setStudentID(Integer.parseInt(idNumberBox.getText()));

                Connection conn = DriverManager.getConnection(connString);
                String sql = "INSERT INTO studentlogin (username, password, studentID) VALUES ('" + login.getUsername() + "', '" + login.getPassword() + "', " + login.getStudentID() + ")";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.executeUpdate(sql);
            } catch (Exception e) {
                System.out.println("Error Message:" + e.getMessage());
            }
            JOptionPane.showMessageDialog(frame,
                    "Student Updated",
                    "Message",
                    JOptionPane.WARNING_MESSAGE);
            this.hide();
            AdminMainForm adminDisplay = new AdminMainForm();
            adminDisplay.show();
        } catch (Exception e) {
            System.out.print("Error Message: " + e.getMessage());
        }
        /*
        AdminViewForm adminView = new AdminViewForm();
         List<StudentLogin> loginList = new ArrayList<StudentLogin>();
        //owList = p.OfficeWorker_SelectAll();

        Object rowData[] = new Object[3];

        DefaultTableModel dtm = (DefaultTableModel) adminView.
        
        //Read from list to populate each row of table
        for (int i = 0; i < loginList.size(); i++) {
            rowData[0] = owList.get(i).getOfficeWorkerId();
            rowData[1] = owList.get(i).getFirstName();
            rowData[2] = owList.get(i).getLastName();

            //Add to table model (display in table)
            dtm.addRow(rowData);
        }*/
    }//GEN-LAST:event_loginSubmitButtonActionPerformed

    private void passwordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordBoxActionPerformed

    private void idNumberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNumberBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNumberBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddLoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField idNumberBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton loginSubmitButton;
    public javax.swing.JTextField passwordBox;
    public javax.swing.JTextField usernameBox;
    // End of variables declaration//GEN-END:variables
}
