/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.Book_Manager;
import domain.Book;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static service.implementation.LibrarySystemImplemenation_JDBC.connString;

/**
 *
 * @author Jaenicx
 */
public class BookReturnForm extends javax.swing.JFrame {

    JFrame frame;

    /**
     * Creates new form BookRentForm
     */
    public BookReturnForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bookReturnButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        isbnDeleteBox = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Return Book");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, -1, -1));

        bookReturnButton.setBackground(new java.awt.Color(51, 51, 255));
        bookReturnButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        bookReturnButton.setForeground(new java.awt.Color(255, 255, 255));
        bookReturnButton.setText("Submit");
        bookReturnButton.setBorder(null);
        bookReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookReturnButtonActionPerformed(evt);
            }
        });
        jPanel2.add(bookReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 130, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Book ISBN:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        isbnDeleteBox.setBackground(new java.awt.Color(51, 51, 255));
        isbnDeleteBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        isbnDeleteBox.setForeground(new java.awt.Color(255, 255, 255));
        isbnDeleteBox.setBorder(null);
        isbnDeleteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnDeleteBoxActionPerformed(evt);
            }
        });
        jPanel2.add(isbnDeleteBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 257, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 0, 320, 600));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 550, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookReturnButtonActionPerformed
        // TODO add your handling code here:
        try {
           //Book_Manager bookDelete = new Book_Manager();
            //bookDelete.book_Delete(Integer.parseInt(isbnDeleteBox.getText()));

            Book book = new Book();
            book.setIsbn(Integer.parseInt(isbnDeleteBox.getText()));

            Connection conn = DriverManager.getConnection(connString);
            String sql = "DELETE FROM book WHERE isbn = " + book.getIsbn() + "";

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.executeUpdate(sql);
        } catch (Exception e) {
            System.out.println("Error Message:" + e.getMessage());
        }
        JOptionPane.showMessageDialog(frame,
                "Books Returned",
                "Message",
                JOptionPane.WARNING_MESSAGE);
        this.hide();
        StudentMainForm studentDisplay = new StudentMainForm();
        studentDisplay.show();

    }//GEN-LAST:event_bookReturnButtonActionPerformed

    private void isbnDeleteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnDeleteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnDeleteBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookReturnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookReturnForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookReturnButton;
    public javax.swing.JTextField isbnDeleteBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
