/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.Student_Manager;
import domain.Student;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static service.implementation.LibrarySystemImplemenation_JDBC.connString;
import domain.Student;
import service.implementation.LibrarySystemImplemenation_JDBC;



/**
 *
 * @author Jaenicx
 */
public class CredentialsForm extends javax.swing.JFrame {
 JFrame frame = null;
    /**
     * Creates new form CredentialsForm
     */
    public CredentialsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        fnameBox = new javax.swing.JTextField();
        credentialsButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lnameBox = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        mailBox = new javax.swing.JTextField();
        studentIDBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Credentials");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 257, 20));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 257, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        fnameBox.setBackground(new java.awt.Color(51, 51, 255));
        fnameBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        fnameBox.setForeground(new java.awt.Color(255, 255, 255));
        fnameBox.setBorder(null);
        fnameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameBoxActionPerformed(evt);
            }
        });
        jPanel2.add(fnameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, 30));

        credentialsButton.setBackground(new java.awt.Color(51, 51, 255));
        credentialsButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        credentialsButton.setForeground(new java.awt.Color(255, 255, 255));
        credentialsButton.setText("Submit");
        credentialsButton.setBorder(null);
        credentialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credentialsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(credentialsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 80, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lnameBox.setBackground(new java.awt.Color(51, 51, 255));
        lnameBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lnameBox.setForeground(new java.awt.Color(255, 255, 255));
        lnameBox.setBorder(null);
        lnameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameBoxActionPerformed(evt);
            }
        });
        jPanel2.add(lnameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 220, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 257, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 257, 20));

        mailBox.setBackground(new java.awt.Color(51, 51, 255));
        mailBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        mailBox.setForeground(new java.awt.Color(255, 255, 255));
        mailBox.setBorder(null);
        mailBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailBoxActionPerformed(evt);
            }
        });
        jPanel2.add(mailBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 220, 30));

        studentIDBox.setBackground(new java.awt.Color(51, 51, 255));
        studentIDBox.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        studentIDBox.setForeground(new java.awt.Color(255, 255, 255));
        studentIDBox.setBorder(null);
        studentIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDBoxActionPerformed(evt);
            }
        });
        jPanel2.add(studentIDBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 330, 660));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameBoxActionPerformed

    private void credentialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credentialsButtonActionPerformed
        // TODO add your handling code here:
       
        try{
       Student_Manager stu = new Student_Manager();
       stu.student_Insert(Integer.parseInt(studentIDBox.getText()) , fnameBox.getText(), lnameBox.getText(), mailBox.getText());
      // LibrarySystemImplemenation_JDBC lib = new LibrarySystemImplemenation_JDBC();
      // lib.student_Insert(Integer.parseInt(studentIDBox.getText()), fnameBox.getText(), lnameBox.getText(), mailBox.getText());
         try {
             //Student student = new Student();
             //LibrarySystemImplemenation_JDBC lib = new LibrarySystemImplemenation_JDBC();
             //lib.student_Insert(student);
             /*
            Student student = new Student();
            student.setStudentID(Integer.parseInt(studentIDBox.getText()));
            student.setFirstName(fnameBox.getText());
            student.setLastName(lnameBox.getText());
            student.setEmail(mailBox.getText());
            
            Connection conn = DriverManager.getConnection(connString);
            String sql = "INSERT INTO student (studentID, firstName, lastName, email) VALUES (" + student.getStudentID() + ",'" + student.getFirstName() + "','" + student.getLastName() + "','" + student.getEmail() + "')";

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.executeUpdate(sql); */
        } catch (Exception e) {
            System.out.println("Error Message:" + e.getMessage());
        }
       JOptionPane.showMessageDialog(frame,
                    "Credentials Added",
                    "Message",
                    JOptionPane.WARNING_MESSAGE);
            this.hide();
            StudentMainForm studentDisplay = new StudentMainForm();
            studentDisplay.show();
        }catch(Exception e){
            System.out.print("Error Message: " +e.getMessage());
        }
        
        

        
    }//GEN-LAST:event_credentialsButtonActionPerformed

    private void lnameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameBoxActionPerformed

    private void mailBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailBoxActionPerformed

    private void studentIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CredentialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CredentialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CredentialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CredentialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CredentialsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton credentialsButton;
    public javax.swing.JTextField fnameBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField lnameBox;
    public javax.swing.JTextField mailBox;
    public javax.swing.JTextField studentIDBox;
    // End of variables declaration//GEN-END:variables

}
