/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

/**
 *
 * @author Jaenicx
 */
public class StudentMainForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentMainForm
     */
    public StudentMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        studentAddCredentials = new javax.swing.JButton();
        addBook = new javax.swing.JButton();
        viewBook = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, -1, -1));

        studentAddCredentials.setBackground(new java.awt.Color(51, 51, 255));
        studentAddCredentials.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        studentAddCredentials.setForeground(new java.awt.Color(255, 255, 255));
        studentAddCredentials.setText("Add Crentials");
        studentAddCredentials.setBorder(null);
        studentAddCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAddCredentialsActionPerformed(evt);
            }
        });
        jPanel2.add(studentAddCredentials, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, 40));

        addBook.setBackground(new java.awt.Color(51, 51, 255));
        addBook.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        addBook.setForeground(new java.awt.Color(255, 255, 255));
        addBook.setText("Add Book");
        addBook.setBorder(null);
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        jPanel2.add(addBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 130, 40));

        viewBook.setBackground(new java.awt.Color(51, 51, 255));
        viewBook.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        viewBook.setForeground(new java.awt.Color(255, 255, 255));
        viewBook.setText("Return Books");
        viewBook.setBorder(null);
        viewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookActionPerformed(evt);
            }
        });
        jPanel2.add(viewBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 0, 320, 600));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 550, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBookActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // TODO add your handling code here:
        this.hide();
        BookRentForm rent = new BookRentForm();
        rent.show();
    }//GEN-LAST:event_addBookActionPerformed

    private void studentAddCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAddCredentialsActionPerformed
        // TODO add your handling code here:
        CredentialsForm credentialsDisplay = new CredentialsForm();
        this.hide();
        credentialsDisplay.show();
    }//GEN-LAST:event_studentAddCredentialsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton studentAddCredentials;
    private javax.swing.JButton viewBook;
    // End of variables declaration//GEN-END:variables
}
